/// Flutter icons SinittIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SinittIcons
///      fonts:
///       - asset: fonts/SinittIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SinittIcons {
  SinittIcons._();

  static const _kFontFam = 'SinittIcons';
  static const String? _kFontPkg = null;

  static const IconData icono_accidente = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_accidente_circular = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_camara = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_camara_circular = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_capa_camaras = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_capa_fotodeteccion = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_capa_fotodeteccion_cuadrada = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_capa_peajes = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_carretera_clima = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_carretera_clima_circular = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_carretera_noclima = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_carretera_noclima_circular = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_condiciones = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_condicion_superficie = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_condicion_superficie_circular = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_deteccion = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_deteccion_circular = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_gestion_carretera = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_gestion_carretera_circular = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_gestion_red = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_gestion_red_circular = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_gestion_velocidad = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_gestion_velocidad_circular = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_infraestructura_danada = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_infraestructura_danada_circular = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_infraestructura_da_ada = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_instrucciones_generales = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_instrucciones_generales_circular = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_malas_condiciones = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_malas_condiciones_circular = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_not_found = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_obstruccion_ambiental = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_obstruccion_ambiental_circular = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_obstruccion_animal = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_obstruccion_animal_circular = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_obstruccion_general = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_obstruccion_general_circular = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_obstruccion_vehicular = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_obstruccion_vehicular_circular = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_peaje = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_peaje_circular = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_peajes = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_senal_foto = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_situaciones = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_situaciones_circular = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_trabajo_construccion = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_trabajo_construccion_circular = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_trabajo_mantenimiento = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_trabajo_mantenimiento_circular = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_trafico = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_trafico_anormal_circular = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_trafico_anormal = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_trafico_circular = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icono_user = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
