
import 'package:flutter/widgets.dart';
/// Flutter icons SinittIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SinittIcons
///      fonts:
///       - asset: fonts/SinittIcons.ttf
///
/// 
///
class SinittIcons {
  SinittIcons._();

  static const _kFontFam = 'SinittIcons';
  static const String? _kFontPkg = null;

  static const IconData iconoAccidente = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoAccidenteCircular = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCamara = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCamaraCircular = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCapaCamaras = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCapaFotodeteccion = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCapaFotodeteccionCuadrada = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCapaPeajes = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCarreteraClima = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCarreteraClimaCircular = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCarreteraNoclima = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCarreteraNoclimaCircular = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCondiciones = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCondicionSuperficie = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoCondicionSuperficieCircular = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoDeteccion = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoDeteccionCircular = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoGestionCarretera = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoGestionCarreteraCircular = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoGestionRed = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoGestionRedCircular = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoGestionVelocidad = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoGestionVelocidadCircular = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoInfraestructuraDanada = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoInfraestructuraDanadaCircular = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoInfraestructuraDaNada = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoInstruccionesGenerales = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoInstruccionesGeneralesCircular = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoMalasCondiciones = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoMalasCondicionesCircular = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoNotFound = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoObstruccionAmbiental = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoObstruccionAmbientalCircular = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoObstruccionAnimal = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoObstruccionAnimalCircular = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoObstruccionGeneral = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoObstruccionGeneralCircular = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoObstruccionVehicular = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoObstruccionVehicularCircular = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoPeaje = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoPeajeCircular = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoPeajes = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoSenalFoto = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoSituaciones = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoSituacionesCircular = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoTrabajoConstruccion = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoTrabajoConstruccionCircular = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoTrabajoMantenimiento = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoTrabajoMantenimientoCircular = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoTrafico = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoTraficoAnormalCircular = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoTraficoAnormal = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoTraficoCircular = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoUser = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
